"""Add rating_history to CFHandle

Revision ID: 8bab2625b011
Revises: 959529456940
Create Date: 2026-08-09 17:49:43.545072+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bab2625b011'
down_revision: Union[str, None] = '959529456940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cf_handles', sa.Column('rating_history', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cf_handles', 'rating_history')
    # ### end Alembic commands ###
