"""add snippets table

Revision ID: d740a0db2cca
Revises: 5aec50897968
Create Date: 2026-08-15 18:49:59.736859+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd740a0db2cca'
down_revision: Union[str, None] = '5aec50897968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snippets',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('complexity', sa.String(length=100), nullable=True),
    sa.Column('usage_notes', sa.Text(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snippets_category'), 'snippets', ['category'], unique=False)
    op.create_index(op.f('ix_snippets_is_official'), 'snippets', ['is_official'], unique=False)
    op.create_index(op.f('ix_snippets_language'), 'snippets', ['language'], unique=False)
    op.create_index(op.f('ix_snippets_user_id'), 'snippets', ['user_id'], unique=False)
    op.create_table('snippet_favorites',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('snippet_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snippet_id'], ['snippets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snippet_favorites_snippet_id'), 'snippet_favorites', ['snippet_id'], unique=False)
    op.create_index(op.f('ix_snippet_favorites_user_id'), 'snippet_favorites', ['user_id'], unique=False)
    op.create_index('ix_snippet_favorites_user_snippet', 'snippet_favorites', ['user_id', 'snippet_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snippet_favorites_user_snippet', table_name='snippet_favorites')
    op.drop_index(op.f('ix_snippet_favorites_user_id'), table_name='snippet_favorites')
    op.drop_index(op.f('ix_snippet_favorites_snippet_id'), table_name='snippet_favorites')
    op.drop_table('snippet_favorites')
    op.drop_index(op.f('ix_snippets_user_id'), table_name='snippets')
    op.drop_index(op.f('ix_snippets_language'), table_name='snippets')
    op.drop_index(op.f('ix_snippets_is_official'), table_name='snippets')
    op.drop_index(op.f('ix_snippets_category'), table_name='snippets')
    op.drop_table('snippets')
    # ### end Alembic commands ###
