"""Add DailyMission and User timezone

Revision ID: 7647d18e5ea0
Revises: d740a0db2cca
Create Date: 2026-08-18 07:17:10.591327+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7647d18e5ea0'
down_revision: Union[str, None] = 'd740a0db2cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_missions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mission_date', sa.Date(), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mission_date', name='uix_daily_mission_user_date')
    )
    op.create_index(op.f('ix_daily_missions_mission_date'), 'daily_missions', ['mission_date'], unique=False)
    op.create_index(op.f('ix_daily_missions_user_id'), 'daily_missions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_index(op.f('ix_daily_missions_user_id'), table_name='daily_missions')
    op.drop_index(op.f('ix_daily_missions_mission_date'), table_name='daily_missions')
    op.drop_table('daily_missions')
    # ### end Alembic commands ###
