"""create problems and feedback tables

Revision ID: a38a3ff300bc
Revises: 8bab2625b011
Create Date: 2026-08-10 04:47:11.210439+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a38a3ff300bc'
down_revision: Union[str, None] = '8bab2625b011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_problem_id', sa.String(length=100), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('index', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('solved_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_contest_id'), 'problems', ['contest_id'], unique=False)
    op.create_index(op.f('ix_problems_platform'), 'problems', ['platform'], unique=False)
    op.create_index(op.f('ix_problems_platform_problem_id'), 'problems', ['platform_problem_id'], unique=True)
    op.create_index(op.f('ix_problems_rating'), 'problems', ['rating'], unique=False)
    op.create_table('recommendation_feedback',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('score_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_feedback_problem_id'), 'recommendation_feedback', ['problem_id'], unique=False)
    op.create_index(op.f('ix_recommendation_feedback_user_id'), 'recommendation_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_feedback_user_id'), table_name='recommendation_feedback')
    op.drop_index(op.f('ix_recommendation_feedback_problem_id'), table_name='recommendation_feedback')
    op.drop_table('recommendation_feedback')
    op.drop_index(op.f('ix_problems_rating'), table_name='problems')
    op.drop_index(op.f('ix_problems_platform_problem_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_platform'), table_name='problems')
    op.drop_index(op.f('ix_problems_contest_id'), table_name='problems')
    op.drop_table('problems')
    # ### end Alembic commands ###
