"""create hints and hint_feedback tables

Revision ID: 79a1b1b8f5b5
Revises: a38a3ff300bc
Create Date: 2026-08-13 16:53:08.257532+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a1b1b8f5b5'
down_revision: Union[str, None] = 'a38a3ff300bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hint_feedback',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hint_feedback_problem_id'), 'hint_feedback', ['problem_id'], unique=False)
    op.create_index(op.f('ix_hint_feedback_user_id'), 'hint_feedback', ['user_id'], unique=False)
    op.create_table('problem_hints',
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'hint_level', name='uix_problem_hint_level')
    )
    op.create_index(op.f('ix_problem_hints_problem_id'), 'problem_hints', ['problem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_hints_problem_id'), table_name='problem_hints')
    op.drop_table('problem_hints')
    op.drop_index(op.f('ix_hint_feedback_user_id'), table_name='hint_feedback')
    op.drop_index(op.f('ix_hint_feedback_problem_id'), table_name='hint_feedback')
    op.drop_table('hint_feedback')
    # ### end Alembic commands ###
