"""add_upsolve_bookmarks_notes

Revision ID: 5aec50897968
Revises: 79a1b1b8f5b5
Create Date: 2026-08-14 18:22:23.288272+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5aec50897968'
down_revision: Union[str, None] = '79a1b1b8f5b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmarks_problem_id'), 'bookmarks', ['problem_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_index('ix_bookmarks_user_problem', 'bookmarks', ['user_id', 'problem_id'], unique=True)
    op.create_table('collections',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_index('ix_collections_user_name', 'collections', ['user_id', 'name'], unique=True)
    op.create_table('problem_notes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_notes_problem_id'), 'problem_notes', ['problem_id'], unique=False)
    op.create_index(op.f('ix_problem_notes_user_id'), 'problem_notes', ['user_id'], unique=False)
    op.create_index('ix_problem_notes_user_problem', 'problem_notes', ['user_id', 'problem_id'], unique=True)
    op.create_table('upsolve_items',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('contest_name', sa.String(length=500), nullable=False),
    sa.Column('problem_index', sa.String(length=20), nullable=False),
    sa.Column('problem_name', sa.String(length=500), nullable=False),
    sa.Column('problem_rating', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('problem_url', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'attempted', 'solved', name='upsolve_status', create_constraint=True), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upsolve_items_status'), 'upsolve_items', ['status'], unique=False)
    op.create_index(op.f('ix_upsolve_items_user_id'), 'upsolve_items', ['user_id'], unique=False)
    op.create_index('ix_upsolve_user_contest_problem', 'upsolve_items', ['user_id', 'contest_id', 'problem_index'], unique=True)
    op.create_index('ix_upsolve_user_status', 'upsolve_items', ['user_id', 'status'], unique=False)
    op.create_table('collection_items',
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('bookmark_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bookmark_id'], ['bookmarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_items_bookmark_id'), 'collection_items', ['bookmark_id'], unique=False)
    op.create_index('ix_collection_items_collection_bookmark', 'collection_items', ['collection_id', 'bookmark_id'], unique=True)
    op.create_index(op.f('ix_collection_items_collection_id'), 'collection_items', ['collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_items_collection_id'), table_name='collection_items')
    op.drop_index('ix_collection_items_collection_bookmark', table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_bookmark_id'), table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index('ix_upsolve_user_status', table_name='upsolve_items')
    op.drop_index('ix_upsolve_user_contest_problem', table_name='upsolve_items')
    op.drop_index(op.f('ix_upsolve_items_user_id'), table_name='upsolve_items')
    op.drop_index(op.f('ix_upsolve_items_status'), table_name='upsolve_items')
    op.drop_table('upsolve_items')
    op.drop_index('ix_problem_notes_user_problem', table_name='problem_notes')
    op.drop_index(op.f('ix_problem_notes_user_id'), table_name='problem_notes')
    op.drop_index(op.f('ix_problem_notes_problem_id'), table_name='problem_notes')
    op.drop_table('problem_notes')
    op.drop_index('ix_collections_user_name', table_name='collections')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index('ix_bookmarks_user_problem', table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_problem_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
