"""Add Submission and UserAnalytics

Revision ID: 959529456940
Revises: 0002
Create Date: 2026-07-15 11:47:33.000698+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '959529456940'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('cf_submission_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('problem_index', sa.String(length=20), nullable=False),
    sa.Column('problem_name', sa.String(length=500), nullable=False),
    sa.Column('problem_rating', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('passed_test_count', sa.Integer(), nullable=False),
    sa.Column('time_consumed_millis', sa.Integer(), nullable=False),
    sa.Column('memory_consumed_bytes', sa.Integer(), nullable=False),
    sa.Column('creation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_cf_submission_id'), 'submissions', ['cf_submission_id'], unique=True)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_index('ix_submissions_user_id_verdict', 'submissions', ['user_id', 'verdict'], unique=False)
    op.create_table('user_analytics',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('total_solved', sa.Integer(), nullable=False),
    sa.Column('contest_count', sa.Integer(), nullable=False),
    sa.Column('current_streak_days', sa.Integer(), nullable=False),
    sa.Column('max_streak_days', sa.Integer(), nullable=False),
    sa.Column('topic_mastery', sa.JSON(), nullable=False),
    sa.Column('recommended_problem', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_analytics_user_id'), 'user_analytics', ['user_id'], unique=True)
    op.alter_column('cf_handles', 'sync_status',
               existing_type=postgresql.ENUM('pending', 'syncing', 'completed', 'failed', name='sync_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('cf_handles', 'sync_status',
               existing_type=postgresql.ENUM('pending', 'syncing', 'completed', 'failed', name='sync_status'),
               server_default=sa.text("'pending'::sync_status"),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_analytics_user_id'), table_name='user_analytics')
    op.drop_table('user_analytics')
    op.drop_index('ix_submissions_user_id_verdict', table_name='submissions')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_cf_submission_id'), table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
